name: 'Continuous Integrations'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    name: 'Run ESLint and Prettier'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Setup Node.js and pnpm'
        uses: './.github/actions/setup'

      - name: 'Execute the lint script'
        run: 'pnpm lint'

  test:
    name: 'Run unit tests with Jest and upload Coverage'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Setup Node.js and pnpm'
        uses: './.github/actions/setup'

      - name: 'Execute the test script'
        run: 'pnpm test'

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  bundle:
    name: 'Bundle package with Rollup.js'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout the repository'
        uses: 'actions/checkout@v4'

      - name: 'Setup Node.js and pnpm'
        uses: './.github/actions/setup'

      - name: 'Execute the build script'
        run: 'pnpm build'
